# Generated by Django 4.0.6 on 2022-08-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='transaction',
        ),
    ]
