# Generated by Django 4.0.6 on 2022-08-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_receipt_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
