# Generated by Django 4.0.6 on 2022-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_customer_adress_customer_age_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
