# Generated by Django 4.0.6 on 2022-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_picture/'),
        ),
    ]
