# Generated by Django 4.0.6 on 2022-10-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
    ]
